### ISSUE TITLE
RGBT的显著性图的百度云链接打不开了。

### ISSUE THREAD

**Issue by hehaiyang111** [lz118/Multi-interactive-Siamese-Decoder-for-RGBT-Salient-Object-Detection#2]

**Comment by lz118** [comment]
你好，链接已更新。

**Comment by Leno-B** [comment]
The shared saliency file has expired. Please share it again.

**Comment by lz118** [comment]
> The shared saliency file has expired. Please share it again.
The shared links have been updated.

**Comment by Leno-B** [comment]
> > The shared saliency file has expired. Please share it again.
> > The shared links have been updated.

Thanks!
